### ISSUE TITLE
"A Quick Guide to Using Keycloak With Spring Boot" does not work with Spring Boot 3

### ISSUE THREAD

**Issue by rweisleder** [eugenp/tutorials#14750]
The current version of the [mentioned article](https://www.baeldung.com/spring-boot-keycloak) does not work with current release Spring Boot 3.1.3. Copying the code from section "5.3 Configuration Class" leads to compiler errors regarding `HttpSecurity`.

```text
...\SecurityConfiguration.java:24:13
java: authorizeRequests() in org.springframework.security.config.annotation.web.builders.HttpSecurity has been deprecated
...\SecurityConfiguration.java:25:17
java: cannot find symbol
  symbol:   method antMatchers(java.lang.String)
  location: class org.springframework.security.config.annotation.web.configurers.ExpressionUrlAuthorizationConfigurer<org.springframework.security.config.annotation.web.builders.HttpSecurity>.ExpressionInterceptUrlRegistry

... etc
```

**Comment by ulisseslima** [comment]
Hey, @rweisleder.

We have internal tasks to keep articles updated to the latest version of Spring, but it might take a while.

This issue will remain open until then.

**Comment by kasramp** [comment]
Hi @rweisleder - appropriate changes have been applied to the article and the code to work with latest version of Spring Boot 3.x. Thanks
