### ISSUE TITLE
current version does NOT build

### ISSUE THREAD

**Issue by anderskristian** [eugenp/tutorials#7245]
I cannot make maven build the system
It is extreme complex 
Several modules does not exist
There is duplicate dependencies

I would suggest a 100% strategy change, let maven modules be small independent modules with a netto number of dependencies 
NO profiles

And a shell script to call all maven builds - 

I'm a little shocked that this is a tutorial

**Comment by carlolf** [comment]
The same problem I do have. I'm a Gradle user and have problems for compile, because the 'build.gradle' is very incomplete. I have to say, I'm working on Kotlin 1.3.41.
I had to include these dependencies:`compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
	compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
	compile 'com.github.kittinunf.fuel:fuel:2.1.0'
	compile 'com.google.code.gson:gson:2.8.5'
	compile 'uy.kohesive.injekt:injekt-core:1.16.1'
`
With these dependencies I could resolve many errors. But there a more, which are a problem of the source classes itself:
`: /home/carlo/develop/baeldung/tutorials/core-kotlin/src/main/kotlin/com/baeldung/fuel/PostRoutingAPI.kt: (10, 5): Class 'posts' is not abstract and does not implement abstract base class member public abstract val bytes: ByteArray? defined in com.baeldung.fuel.PostRoutingAPI
e: /home/carlo/develop/baeldung/tutorials/core-kotlin/src/main/kotlin/com/baeldung/fuel/PostRoutingAPI.kt: (12, 5): Class 'comments' is not abstract and does not implement abstract base class member public abstract val bytes: ByteArray? defined in com.baeldung.fuel.PostRoutingAPI
e: /home/carlo/develop/baeldung/tutorials/core-kotlin/src/main/kotlin/com/baeldung/fuel/PostRoutingAPI.kt: (38, 27): Type of 'headers' is not a subtype of the overridden property 'public abstract val headers: Map<String, HeaderValues /* = Collection<String> */>? defined in com.github.kittinunf.fuel.util.FuelRouting'
`

**Comment by lor6** [comment]
Hi @anderskristian Yes, there are a lot of projects in the repo, so it's much easier to run the specific project you're interested in rather than the full repository.

After you clone the repo, you can move to the directory of a specific module, and run the Maven command in that location.

Having a single main POM file helps with keeping the common configuration/dependencies in a single place. Otherwise, it would be very difficult to make updates to the configuration in many places. We are looking into other ways to handle such a large number of projects, but, for now, the easiest approach is to build only the project(s) you need instead of the full repo.

Thanks for the feedback.

@carlolf I'll add a ticket to look into the core-kotlin module Gradle build, and let you know of any updates.

**Comment by anderskristian** [comment]
Thanks for the answer
I just wondered ..
Consider you want to teach various maven concepts or  Gradle .. it might also be a problem with one big build ..
Thanks again ...
/Anders
